package enums;

public enum EOrderStatus {
    STATUS_DRAFT,
    STATUS_QUOTED,
    STATUS_CONFIRMED,
    STATUS_FREEZE_REQUESTED,
    STATUS_REJECTED,
    STATUS_ACCEPTED,
    STATUS_ASSIGNED,
    STATUS_IN_PROGRESS,
    STATUS_FINISHED,
    STATUS_CHARGE_REQUESTED,
    STATUS_CLOSED
}
